name: 'Clean Workflow Action'

description: 'Clean workflow run logs based on configuration'

inputs:
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  days_old:
    description: 'The amount of days old to delete'
    required: false
    default: '7'

outputs:
  result:
    description: 'The number of workflows deleted'

runs:
  using: 'node12'
  main: 'dist/index.js'