name: Clean Logs

on:
  workflow_dispatch:
    inputs:
      days_old:
        description: "The amount of days old to delete"
        default: "7"
        required: false
      runs_to_keep:
        description: "The amount of latest workflows runs to keep"
        default: "0"
        required: false

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - uses: igorjs/gh-actions-clean-workflow@main
        with:
          days_old: ${{ github.event.inputs.days_old }}
          runs_to_keep: ${{ github.event.inputs.runs_to_keep }}
